### ISSUE TITLE
Allow search by country codes

### ISSUE THREAD

**Issue by pwr22** [pwr22/covbot#12]
Can't be done through whoosh as it seems to ignore small terms.

- [x] Get a list of country codes.
- [x] Map them to countries in the data.
- [x] Implement a lookup into this table.

**Comment by bertiebaggio** [comment]
Seems to be handled by 98a4111f4859fcf29d8b7c0f5d48dea26feb9771 👍

**Comment by pwr22** [comment]
Yup, done with pycountry
