### ISSUE TITLE
Add details stats on scotland

### ISSUE THREAD

**Issue by pwr22** [pwr22/covbot#22]
https://www.gov.scot/coronavirus-covid-19/

**Comment by bertiebaggio** [comment]
Working on this using [tomwhite/covid-19-uk-data](https://github.com/tomwhite/covid-19-uk-data). It's already done the work of scraping the Scottish Covid19 page. 

Note that repo has historic data too, which might make for interesting features.

Will open WIP PR once I have it working with covbot as opposed to locally :)
