### ISSUE TITLE
Send m.notice

### ISSUE THREAD

**Issue by pwr22** [pwr22/covbot#27]
We are sending `m.text` right now because the WhatsApp bridge doesn't handle `m.notice`. Things to do:

- [x] Add `m.notice` handling to the WhatsApp bridge.
- [x] Change back to `m.notice`.
- [x] Check the Telegram bridge handles them.
- [x] Add m.notice` handling to the Telegram bridge if it doesn't.

**Comment by bertiebaggio** [comment]
**Additional**: in plain non-bridged Riot, preformatted tables aren't rendered in `m.notice` events on mobile clients, only `m.text` are for some reason. As such, I'd suggest

- [ ] keep `!table*` variants as `m.text`

Cheers :)

**Comment by pwr22** [comment]
In riotx it doesn't seem to work even in m.text 😟.

**Comment by bertiebaggio** [comment]
Huh, that's interesting. 

My RiotX version is 0.18.1 [40018012], Matrix SDK 0.0.1, olm 3.1.2; and preformatted tables work there, though HTML tables are not rendered as tables.

My last comment was ambiguous, will edit.

**Comment by pwr22** [comment]
Ah yeah, that's what I meant. HTML tables don't render is what I meant.

I've played around with the tables stuff myself through the different
bridges and stuff and I think I'm settled on making preformatted text the
default choice.

**Comment by pwr22** [comment]
@auscompgeek this is done now :+1:
