### ISSUE TITLE
Add European Centre for Disease Control data

### ISSUE THREAD

**Issue by immunekang** [pwr22/covbot#28]
https://data.europa.eu/euodp/en/data/dataset/covid-19-coronavirus-data

**Comment by immunekang** [comment]
https://www.ecdc.europa.eu/en/novel-coronavirus-china (nothing at this one)

**Comment by pwr22** [comment]
https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

**Comment by pwr22** [comment]
Seems to operate at country level only
